### ISSUE TITLE
Residuals do not have mean 0

### ISSUE THREAD

**Issue by pdeffebach** [hyunseungkang/ivmodel#4]
From the manual:

```
data(card.data)
Y=card.data[,"lwage"]
D=card.data[,"educ"]
Z=card.data[,"nearc4"]
Xname=c("exper", "expersq", "black", "south", "smsa", "reg661",
"reg662", "reg663", "reg664", "reg665", "reg666", "reg667",
"reg668", "smsa66")
X=card.data[,Xname]
foo = ivmodel(Y=Y,D=D,Z=Z,X=X)
resid(foo)
residuals(foo)
```

However note that the mean of residuals is *not* 0, even for OLS

```
r$> mean(resid(foo)[,1])                                                                                      
[1] 4.719285
```

There is no explanation for this behavior in the manual. 

Additionally, in [para.R](https://github.com/hyunseungkang/ivmodel/blob/master/R/para.r), the `para` function does not use the calculated residuals when estimating the variance of the error terms. 

Given that it is not possible to compute the coefficients on the exogenous covariates, I was hoping to use `resid` to estimate `y_hat`. However subtracting residuals from the true value will not yield the correct answer since `resid` does not have mean `0` on any columns. 

Could you please provide more explanation? I would be happy to submit a PR to the documentation if I am under a simple misunderstanding. 

Thank you!

**Comment by hyunseungkang** [comment]
Hello! Thanks for catching the error in both `resid` and `residuals`. They have now been corrected and follow how `para` computes residuals. Running the exact same example above now will produce 

```
> mean(resid(foo)[,1])
[1] -9.652911e-18
```

More generally, now all the k-Class estimators have mean-zero residuals.

```
> colMeans(resid(foo))
          OLS          TSLS          LIML        Fuller 
-9.601205e-18 -1.282082e-17 -1.290006e-17 -1.295279e-17 
```

We are also planning to update this package to include estimated coefficients on the exogenous covariates, by default.

**Comment by pdeffebach** [comment]
Wonderful! thank you!
