### ISSUE TITLE
Error in KClass(ivmodelObject, beta0 = beta0, alpha = alpha, k = k, heteroSE = heteroSE,  :    k is out-of-range; the matrix inversion in the k-class estimator will fail.

### ISSUE THREAD

**Issue by ccmullally** [hyunseungkang/ivmodel#5]
I received the above error when running the code below:
`
ak.table5 <- ivmodelFormula(lwkly ~  educ + factor(region) + factor(yob) + Race + SMSA + Married + Age + Age2 | factor(birthqtr):factor(yob) + factor(region) + factor(yob) + Race + SMSA + Married + Age + Age2, data = df)`

I closely followed the Card vignette in the documentation. I also tried running it with a single IV and no use of factor(). debug() yielded no insights. 

I'm happy to share my data. It is census data used in Angrist and Krueger's quarter-of-birth returns to education study. It has about 1.4 million observations.

**Comment by hyunseungkang** [comment]
Hello! Would it be possible to post the error message from running the code as well as the error message when you run with a single IV without using factor()? This will help me debug any errors in the package.

**Comment by ccmullally** [comment]
The error is what is in the subject line: Error in KClass(ivmodelObject, beta0 = beta0, alpha = alpha, k = k, heteroSE = heteroSE,  : 
  k is out-of-range; the matrix inversion in the k-class estimator will fail.
I ran it with the following code: 
`ak.table5 <- ivmodelFormula(lwkly ~ educ + Race + SMSA + Married + Age + Age2 | q1 + Race + SMSA + Married + Age + Age2, data = df)`
and got the same error

**Comment by hyunseungkang** [comment]
I apologize for the very late response. We are not sure how the variables "lwkly", "yob", "region", etc. in your code are created as the vignette uses different variables. If you can provide the full code that replicates the error, it will help us track down the bug.

**Comment by ccmullally** [comment]
Hi, 
I went back and unfortunately it looks like I did the data prep in Stata. I forgot about this when I initially posted the above comment. Despite that, I have posted the data prep Stata code here. Any variables you do not see created were included in the version of the data I accessed, I believe from Angrist's website but I could be wrong:
`cap log close
set more off
cd "D:/Mullally,Conner/Documents/Dropbox/UF/teaching/phd labor econ UF/Week 9 instrumental variables basics/problem set module 9 IV"
log using dataprep_ps9, replace

use cleandata.dta, clear
drop if incwage==0 | wkswork1 == 0

quietly tab birthqtr, generate(birthqtr_dummy)
qui rename birthqtr_dummy1 q1
qui rename birthqtr_dummy2 q2
qui rename birthqtr_dummy4 q4
qui rename birthqtr_dummy3 q3
qui g yob=.
qui replace yob=1979-age
qui replace yob=1980-age if birthqtr==1
***generate figures
*label drop birthqtrlbl
label define blbl 0 "0"
label define blbl 1 "1", add
label define blbl 2 "2", add
label define blbl 3 "3", add
label define blbl 4 "4", add
label define blbl 9 "9", add 
label values birthqtr blbl
g bqt = yob + .25*(birthqtr-1)


/* A & K say they used completed years of education. The only variables
that have completed years are educ and educd */
replace educ = 0 if educd < 14
replace educ = educd - 13 if educd >= 14 & educd <= 17
replace educ = educd - 17 if educd == 22 | educd == 23
replace educ = educd - 18 if educd == 25 | educd == 26
replace educ = educd - 21 if educd == 30
replace educ = educd - 30 if educd == 40
replace educ = educd - 39 if educd == 50
replace educ = educd - 48 if educd == 60
replace educ = educd - 57 if educd == 70
replace educ = educd - 66 if educd == 80
replace educ = educd - 75 if educd == 90
replace educ = educd - 84 if educd == 100
replace educ = educd - 93 if educd >= 110 & educd <= 113
replace educ = 12 if educd == 65
lab drop educ_lbl

sort bqt
save cleandata2.dta, replace
collapse (mean) educ, by(bqt)
g mavg = (educ[_n - 2] + educ[_n - 1] + educ[_n + 1] + educ[_n + 2])/4
keep bqt mavg
sort bqt
merge 1:m bqt using cleandata2.dta
tab _merge
drop _merge
g detrend=(educ-mavg)

lab var detrend "Total years of education, detrended"
lab var yob "Year of birth"
lab var black "1 = black"
lab var met "1 = center city"
lab var mar "1 = married"
lab var bqt "Quarter of birth, by quarter years (1930 - 1959.75)"

rename met SMSA
rename black Race
rename mar Married
rename detrend educ_detrended

replace age = 1980 - bqt

g hsgrad = (educ >= 12)
lab var hsgrad "1 = high school graduate"
/*
tab yob, g(dyob)
tab bpl, g(dbpl)
tab birthqtr, g(dbqt)
foreach v of varlist dbpl* {
	forv i = 2/4 {
	g `v'Xq`i' = `v'*dbqt`i'
	}
}
foreach v of varlist dyob* {
	forv i = 2/4 {
	g `v'Xq`i' = `v'*dbqt`i'
	}
}
*/
g age2=age*age
rename age Age
lab var Age "Age measured in quarter years"
rename age2 Age2
lab var Age2 "Age squared, age measured in quarter years"
lab var educ "Education"

drop qage qsex qbirthmo qrace qrace2 qeduc qwkswork qincwage mavg datanum ///
pernum perwt metro gq hhwt marst birthyr race raced bpld educd higrade ///
higraded sex
g lwkly = ln(incwage/wkswork1)
lab var lwkly "ln (weekly earnings)"

order incwage lwkly educ educ_detrended Race SMSA Married Age Age2 q1-q4 r1-r9 yob ///
bqt wkswork1 year serial region stateicp statefip 

drop if yob > 1939

sort region stateicp serial
saveold cleandata2.dta, replace version(13)

log close
`

**Comment by hyunseungkang** [comment]
Thanks for the code. I'm still unable to pinpoint the error from the previous error, which again I apologize for the very long delay in getting back to you. But, to the best of my ability, this seems more like a data processing issue when importing data from STATA into R rather than a bug in ivmodel and I've decided to close the issue for now.
