### ISSUE TITLE
Incorrect/inaccurate TSLS estimates?

### ISSUE THREAD

**Issue by michaelpollmann** [hyunseungkang/ivmodel#6]
I'm quite interested in the package functionality overall -- thanks for your work on providing these methods! -- but I stumbled upon some incorrect or inaccurate (?) results that I can't quite figure out without diving deeper into your code, so maybe you have a better understanding of what is going on.

Download the data from here:
https://economics.mit.edu/sites/default/files/inline-files/NEW7080_1.rar
and unpack the .dta file. It is the data corresponding to the Angrist & Kruger (1991) paper using quarter of birth as an instrument for educational attainment in a wage regression.

First, the following code:
```
library(haven)
library(dplyr)
df <- read_dta("../data/NEW7080.dta") %>% 
  rename(AGE = v1,
         EDUC = v4,
         LWKLYWGE = v9,
         QOB = v18) %>% 
  mutate(QTR1 = QOB==1,
         EDUC_norm=scale(EDUC),
         AGE_norm=scale(AGE))
reg_ivmodel <- ivmodel::ivmodel(Y=as.numeric(df$LWKLYWGE),
                                D=as.numeric(df$EDUC),
                                Z=as.matrix(df$QTR1,ncol=1),
                                k=1)
reg_AER <- AER::ivreg(formula = LWKLYWGE ~ EDUC | QTR1,
                      data=df)
y <- as.numeric(df$LWKLYWGE)
X <- cbind(1,df$EDUC)
Z <- cbind(1,df$QTR1)
bhat_manual <- solve(crossprod(Z,X),crossprod(Z,y))

as.numeric(c(reg_ivmodel$kClass$point.est,reg_AER$coefficients["EDUC"],bhat_manual[2]))
```
returns output
```[1] 0.08773427 0.08741479 0.08741479```
Why does ivmodel differ from the "correct" answer here? In principle, it may just be numerical inaccuracies/overflows, but in some other examples (requiring longer code), the difference between ivmodel and the other two methods is more pronounced.

Secondly, when I add the AGE covariate, ivmodel fails:
```
reg_ivmodel <- ivmodel::ivmodel(Y=as.numeric(df$LWKLYWGE),
                 D=as.numeric(df$EDUC),
                 Z=as.matrix(df$QTR1,ncol=1),
                 X=as.matrix(df$AGE,ncol=1),
                 k=1)
```
returns error message
```
Error in KClass(ivmodelObject, beta0 = beta0, alpha = alpha, k = k, heteroSE = heteroSE,  : 
  k is out-of-range; the matrix inversion in the k-class estimator will fail.
```

Note that this is not due to collinearity between covariate and instrument. The alternative estimators work just fine:
```
reg_AER <- AER::ivreg(formula = LWKLYWGE ~ EDUC + AGE | QTR1 + AGE,
                  data=df)

y <- as.numeric(df$LWKLYWGE)
X <- cbind(1,df$EDUC,df$AGE)
Z <- cbind(1,df$QTR1,df$AGE)
bhat_manual <- solve(crossprod(Z,X),crossprod(Z,y))

as.numeric(c(reg_AER$coefficients["EDUC"],bhat_manual[2]))
```
returns output
```
[1] 0.5120103 0.5120103
```

Note that using *both* normalized EDUC and normalized AGE fixes the error message:
```
reg_ivmodel <- ivmodel::ivmodel(Y=as.numeric(df$LWKLYWGE),
                                D=as.numeric(df$EDUC_norm),
                                Z=as.matrix(df$QTR1,ncol=1),
                                X=as.matrix(df$AGE_norm,ncol=1),
                                k=1)
reg_ivmodel$kClass$point.est/sd(df$EDUC)
```
*but* the point estimate is still off. The output of the above code is
```
   Estimate
1 0.4878251
```
which is slightly too small (the correct estimate is 0.51 rather than 0.49)

The covariance matrix of the un-normalized data is somewhat but not very uneven:
```
var(df[c("LWKLYWGE","EDUC","QTR1","AGE")])
```
returns output
```
             LWKLYWGE       EDUC         QTR1        AGE
LWKLYWGE  0.517322860  0.8707981 -0.001965714 -0.4766640
EDUC      0.870798134 10.6944078 -0.022487202 -4.0259169
QTR1     -0.001965714 -0.0224872  0.185658401  0.2111851
AGE      -0.476664031 -4.0259169  0.211185124 35.0497559
```

I would love to hear why the issues described above arise. Given the relatively simple nature of the example (very small number of variables, exact identification), if this example can already produce noticeable numerical inaccuracies, I am slightly worried about the quality of estimates in larger examples and for more complicated estimators.

**Comment by hyunseungkang** [comment]
Thank you for raising this issue and I'm terribly sorry for the very, very late reply. Overall, thank you for pointing out the bugs; they are now fixed and agree with manually computed estimates and the AER package.

For your first point: There was a bug on how we treat internally treat and store logical vectors (i.e. True/False) with numeric vectors (i.e. 1/0) and this was causing this issue. Specifically, if you replace `Z=as.matrix(df$QTR1,ncol=1)` with `Z=as.numeric(as.matrix(df$QTR1))` in the argument for `ivmodel::ivmodel()`, ivmodel's estimates agree with AER and the manually computed estimates. Here is a replication code to demonstrate this:

```
y <- as.numeric(df$LWKLYWGE)
X <- cbind(1,df$EDUC)
Z <- cbind(1,df$QTR1)
bhat_manual <- solve(crossprod(Z,X),crossprod(Z,y))

reg_ivmodel <- ivmodel::ivmodel(Y=as.numeric(df$LWKLYWGE),
                                D=as.numeric(df$EDUC),
                                Z=as.numeric(as.matrix(df$QTR1,ncol=1)),
                                k=1)
reg_AER <- AER::ivreg(formula = LWKLYWGE ~ EDUC | QTR1,
                      data=df)                      
as.numeric(c(reg_ivmodel$kClass$point.est,reg_AER$coefficients["EDUC"],bhat_manual[2]))
```

This returns the output

```
[1] 0.08741478 0.08741479 0.08741479
```

The error is now fixed. You should be able to directly input the logical vector as an instrument and your original command returns the correct output.
```
reg_ivmodel <- ivmodel::ivmodel(Y=as.numeric(df$LWKLYWGE),
                                D=as.numeric(df$EDUC),
                                Z=as.matrix(df$QTR1,ncol=1),
                                k=1)
reg_ivmodel$kClass$point.est
```
The output should be:
```
    Estimate
1 0.08741478
```

For the second point: There was a bug on how we calculate rank. Now, the 

```
reg_ivmodel <- ivmodel::ivmodel(Y=as.numeric(df$LWKLYWGE),
                 D=as.numeric(df$EDUC),
                 Z=as.matrix(df$QTR1,ncol=1),
                 X=as.matrix(df$AGE,ncol=1),
                 k=1)
reg_AER <- AER::ivreg(formula = LWKLYWGE ~ EDUC + AGE | QTR1 + AGE,
                  data=df)

y <- as.numeric(df$LWKLYWGE)
X <- cbind(1,df$EDUC,df$AGE)
Z <- cbind(1,df$QTR1,df$AGE)
bhat_manual <- solve(crossprod(Z,X),crossprod(Z,y))

as.numeric(c(reg_ivmodel$kClass$point.est,reg_AER$coefficients["EDUC"],bhat_manual[2]))
``` 
The output should be:
```
[1] 0.5120106 0.5120103 0.5120103
```

I'm not 100% sure about the issues with normalization. However, given that the k-class issue is resolved, I hope that the question you had about the second point is addressed.

**Comment by michaelpollmann** [comment]
thank you for your work on this and the update, that sounds good!
